#!/bin/bash
FILENAME=`basename -s .mov "$1"`
FRAMERATE=`ffprobe -v error -select_streams v:0 -show_entries stream=r_frame_rate -of default=noprint_wrappers=1:nokey=1 "$1" | bc -l `
ffmpeg -i "$1" -i ~/Documents/NFA_Color_22.png -filter_complex "scale=640:-1[cuda];[1]scale=w=iw/2:h=ih/2[l];[cuda][l]overlay=W/1.3 [logo]; [logo] drawtext=fontfile=/Users/digilab/Documents/executive.otf:x=225:y=40" -pix_fmt yuv420p -b:v 5000k -c:v mpeg2video -c:a pcm_s16le `basename -s .mov "$FILENAME"`"_MPEG.mpg"
