#!/bin/bash
FILENAME=`basename -s .mov "$1"`
#FRAMERATE=`mediainfo "$1" | grep "Frame rate" | head -n 34 | tail -n 1 | awk '{print $4}'`
FRAMERATE=`ffprobe -v error -select_streams v:0 -show_entries stream=r_frame_rate -of default=noprint_wrappers=1:nokey=1 "$1" | bc -l `
ffmpeg -i "$1" -i ~/Documents/NFA_Color_22.png -filter_complex "scale=640:-1[cuda];[1]scale=w=iw/2:h=ih/2[l];[cuda][l]overlay=W/1.3 [logo]; [logo] drawtext=fontfile=/Users/digilab/Documents/executive.otf:x=225:y=40:fontcolor=white:fontsize=32:r="$FRAMERATE":timecode='00\:00\:00\:00'" -pix_fmt yuv420p -refs 4 -map_metadata -1 -movflags +faststart -b:v 1500k -b:a 128k -c:v libx264 -c:a aac -threads 8 `basename -s .mov "$FILENAME"`"_SCREENER.mp4"
